# Generated by Django 3.0.8 on 2021-08-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('workclass', models.CharField(max_length=20)),
                ('final_weight', models.IntegerField()),
                ('education', models.CharField(max_length=20)),
                ('education_num', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('capital_gain', models.IntegerField()),
                ('capital_loos', models.IntegerField()),
                ('hour_per_week', models.IntegerField()),
                ('native_country', models.CharField(max_length=20)),
                ('income', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Census',
            },
        ),
    ]
