# Generated by Django 3.0.8 on 2021-08-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineLearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('biblioteca_usada', models.CharField(max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
